import streamlit as st
import datetime
import requests
import sys


BASE_URL = "http://localhost:8000"  #backend endpoint


st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)


st.title("🌍 Travel Planner Agentic Application")


#initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []


st.header("How can i help you in planning a trip? Let me know where do you wanna go.")


with st.form(key="query_form", clear_on_submit=True):
    submit_button=st.form_submit_button("Send")
    user_input=st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")

if submit_button and user_input.strip():
    try:
        # show user message
        # show thinking spinner while backed processes
        with st.spinner("Bot is thinking..."):
            payload= {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated: ** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by:** Atriyo's Travel Agent


            ---

            {answer}


            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, oper

            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: "+ response.text)

    except Exception as e:
        raise f"The reponse failed due to {e}"